coco_vqa_val:
  image_path: "/data/kiriti/MiniGPT-4/dataset/coco/images/val2014"
  question_path: "/dataset/coco/annotations/v2_OpenEnded_mscoco_val2014_questions.json"
  answer_path: "/dataset/coco/annotations/v2_mscoco_val2014_annotations.json"
  split: "val"
